version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src/scrape" 
    schedule:
      interval: "weekly" 
  - package-ecosystem: "npm"
    directory: "/src/scrape" 
    schedule:
      interval: "weekly"